/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbcrud;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JPanel;
import tabelas.*;

/**
 * @author Tomás Abril
 * @author Daniel Silva Curi
 */
public class Janela extends javax.swing.JFrame {

    EntityManagerFactory emf;
    EntityManager em;

    int x = 2;
    JPanel lastpanel = new JPanel();

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();

        //fazer conexao com o banco de dados
        emf = Persistence.createEntityManagerFactory("DbCRUDPU");
        em = emf.createEntityManager();

        lastpanel = gen_pan;
    }

    private void trocaTela(JPanel newpanel) {
        lastpanel.setVisible(false);
        newpanel.setVisible(true);
        lastpanel = newpanel;
        opc_panel.setLayer(lastpanel, x++);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diag_ins_gen = new javax.swing.JDialog();
        ins_gen_but = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ins_gen_desc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ins_gen_id = new javax.swing.JTextField();
        diag_ins_liv = new javax.swing.JDialog();
        ins_liv_but = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ins_liv_edi = new javax.swing.JTextField();
        ins_liv_id = new javax.swing.JTextField();
        ins_liv_gen = new javax.swing.JTextField();
        ins_liv_ano = new javax.swing.JTextField();
        ins_liv_pre = new javax.swing.JTextField();
        ins_liv_des = new javax.swing.JTextField();
        ins_liv_res = new javax.swing.JTextField();
        ins_liv_est = new javax.swing.JTextField();
        ins_liv_aut = new javax.swing.JTextField();
        ins_liv_tit = new javax.swing.JTextField();
        diag_ins_ped = new javax.swing.JDialog();
        ins_ped_but = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        ins_ped_usu = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        ins_ped_ped = new javax.swing.JTextField();
        ins_ped_dat = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        ins_ped_pag = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        diag_cons_gen = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        cons_gen_id = new javax.swing.JTextField();
        cons_gen_but = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cons_gen_res = new javax.swing.JTextArea();
        diag_cons_liv = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        cons_liv_id = new javax.swing.JTextField();
        cons_liv__but = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cons_liv_res = new javax.swing.JTextArea();
        diag_cons_ped = new javax.swing.JDialog();
        jLabel47 = new javax.swing.JLabel();
        cons_ped_id = new javax.swing.JTextField();
        cons_ped_but = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        cons_ped_res = new javax.swing.JTextArea();
        diag_alt_gen = new javax.swing.JDialog();
        alt_gen_but = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        alt_gen_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        alt_gen_desc = new javax.swing.JTextField();
        diag_alt_liv = new javax.swing.JDialog();
        alt_liv_but = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        alt_liv_id = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        alt_liv_gen = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        alt_liv_des = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        alt_liv_res = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        alt_liv_pre = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        alt_liv_est = new javax.swing.JTextField();
        alt_liv_tit = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        alt_liv_aut = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        alt_liv_edi = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        alt_liv_ano = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        diag_alt_ped = new javax.swing.JDialog();
        alt_ped_but = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        alt_ped_ped = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        alt_ped_usu = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        alt_ped_dat = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        alt_ped_pag = new javax.swing.JTextField();
        diag_exc_gen = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        exc_gen_id = new javax.swing.JTextField();
        exc_gen_but = new javax.swing.JButton();
        diag_exc_liv = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        exc_liv_id = new javax.swing.JTextField();
        exc_liv_but = new javax.swing.JButton();
        diag_exc_ped = new javax.swing.JDialog();
        jLabel52 = new javax.swing.JLabel();
        exc_ped_id = new javax.swing.JTextField();
        exc_ped_but = new javax.swing.JButton();
        butg_Tabelas = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        opc_panel = new javax.swing.JLayeredPane();
        gen_pan = new javax.swing.JPanel();
        ins_gen = new javax.swing.JButton();
        alt_gen = new javax.swing.JButton();
        exc_gen = new javax.swing.JButton();
        cons_gen = new javax.swing.JButton();
        liv_pan = new javax.swing.JPanel();
        ins_liv = new javax.swing.JButton();
        alt_liv = new javax.swing.JButton();
        exc_liv = new javax.swing.JButton();
        cons_liv = new javax.swing.JButton();
        ped_pan = new javax.swing.JPanel();
        ins_ped = new javax.swing.JButton();
        alt_ped = new javax.swing.JButton();
        exc_ped = new javax.swing.JButton();
        cons_ped = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ped_but = new javax.swing.JToggleButton();
        liv_but = new javax.swing.JToggleButton();
        gen_but = new javax.swing.JToggleButton();

        diag_ins_gen.setTitle("Inserir Gênero");
        diag_ins_gen.setMinimumSize(null);
        diag_ins_gen.setModal(true);
        diag_ins_gen.setResizable(false);

        ins_gen_but.setText("Inserir");
        ins_gen_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_gen_butActionPerformed(evt);
            }
        });

        jLabel10.setText("Descrição:");

        jLabel3.setText("ID:");

        javax.swing.GroupLayout diag_ins_genLayout = new javax.swing.GroupLayout(diag_ins_gen.getContentPane());
        diag_ins_gen.getContentPane().setLayout(diag_ins_genLayout);
        diag_ins_genLayout.setHorizontalGroup(
            diag_ins_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ins_genLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_ins_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ins_gen_but)
                    .addGroup(diag_ins_genLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_gen_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diag_ins_genLayout.setVerticalGroup(
            diag_ins_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ins_genLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_ins_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ins_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ins_gen_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ins_gen_but)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diag_ins_liv.setTitle("Inserir Livro");
        diag_ins_liv.setMaximumSize(null);
        diag_ins_liv.setModal(true);
        diag_ins_liv.setResizable(false);

        ins_liv_but.setText("Inserir");
        ins_liv_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_liv_butActionPerformed(evt);
            }
        });

        jLabel15.setText("Título:");

        jLabel16.setText("ID:");

        jLabel24.setText("Autor:");

        jLabel25.setText("Editora:");

        jLabel26.setText("Ano:");

        jLabel27.setText("GENERO_ID:");

        jLabel28.setText("Descrição:");

        jLabel29.setText("Preço:");

        jLabel30.setText("Reserva:");

        jLabel31.setText("Estoque:");

        ins_liv_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_liv_genActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_ins_livLayout = new javax.swing.GroupLayout(diag_ins_liv.getContentPane());
        diag_ins_liv.getContentPane().setLayout(diag_ins_livLayout);
        diag_ins_livLayout.setHorizontalGroup(
            diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_ins_livLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_des))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_tit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, diag_ins_livLayout.createSequentialGroup()
                        .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, diag_ins_livLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ins_liv_edi))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, diag_ins_livLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ins_liv_aut, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(diag_ins_livLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ins_liv_ano))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_ins_livLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ins_liv_gen, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_pre, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_est, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(diag_ins_livLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ins_liv_res))
                            .addGroup(diag_ins_livLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ins_liv_but)))))
                .addContainerGap())
        );
        diag_ins_livLayout.setVerticalGroup(
            diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ins_livLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(ins_liv_tit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(ins_liv_aut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(ins_liv_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_liv_edi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(ins_liv_gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(ins_liv_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_liv_pre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(ins_liv_est, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(ins_liv_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(26, 26, 26)
                .addComponent(ins_liv_but)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diag_ins_ped.setTitle("Inserir Pedido");
        diag_ins_ped.setMaximumSize(null);
        diag_ins_ped.setMinimumSize(null);
        diag_ins_ped.setModal(true);
        diag_ins_ped.setResizable(false);

        ins_ped_but.setText("Inserir");
        ins_ped_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_ped_butActionPerformed(evt);
            }
        });

        jLabel44.setText("USUARIO_ID:");

        jLabel45.setText("PEDIDO_ID:");

        ins_ped_dat.setText("2008-7-04");
        ins_ped_dat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_ped_datActionPerformed(evt);
            }
        });

        jLabel53.setText("Data:");

        jLabel54.setText("Pagamento:");

        javax.swing.GroupLayout diag_ins_pedLayout = new javax.swing.GroupLayout(diag_ins_ped.getContentPane());
        diag_ins_ped.getContentPane().setLayout(diag_ins_pedLayout);
        diag_ins_pedLayout.setHorizontalGroup(
            diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_ins_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(diag_ins_pedLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ins_ped_but))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, diag_ins_pedLayout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_ped_ped, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_ped_usu, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, diag_ins_pedLayout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_ped_dat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_ped_pag)))
                .addContainerGap())
        );
        diag_ins_pedLayout.setVerticalGroup(
            diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ins_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ins_ped_ped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel44)
                    .addComponent(ins_ped_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(ins_ped_dat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54)
                    .addComponent(ins_ped_pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ins_ped_but)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diag_cons_gen.setTitle("Consultar Gêneros");
        diag_cons_gen.setMaximumSize(null);
        diag_cons_gen.setMinimumSize(null);
        diag_cons_gen.setModal(true);
        diag_cons_gen.setResizable(false);

        jLabel4.setText("ID:");

        cons_gen_but.setText("Consultar");
        cons_gen_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_gen_butActionPerformed(evt);
            }
        });

        cons_gen_res.setColumns(20);
        cons_gen_res.setRows(5);
        cons_gen_res.setEnabled(false);
        cons_gen_res.setFocusable(false);
        jScrollPane1.setViewportView(cons_gen_res);

        javax.swing.GroupLayout diag_cons_genLayout = new javax.swing.GroupLayout(diag_cons_gen.getContentPane());
        diag_cons_gen.getContentPane().setLayout(diag_cons_genLayout);
        diag_cons_genLayout.setHorizontalGroup(
            diag_cons_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_genLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(diag_cons_genLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cons_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cons_gen_but)))
                .addContainerGap())
        );
        diag_cons_genLayout.setVerticalGroup(
            diag_cons_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_genLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(diag_cons_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cons_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cons_gen_but)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diag_cons_liv.setTitle("Consultar Livros");
        diag_cons_liv.setMaximumSize(null);
        diag_cons_liv.setMinimumSize(null);
        diag_cons_liv.setModal(true);
        diag_cons_liv.setResizable(false);

        jLabel18.setText("ID:");

        cons_liv__but.setText("Consultar");
        cons_liv__but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_liv__butActionPerformed(evt);
            }
        });

        cons_liv_res.setColumns(20);
        cons_liv_res.setRows(5);
        cons_liv_res.setEnabled(false);
        cons_liv_res.setFocusable(false);
        jScrollPane2.setViewportView(cons_liv_res);

        javax.swing.GroupLayout diag_cons_livLayout = new javax.swing.GroupLayout(diag_cons_liv.getContentPane());
        diag_cons_liv.getContentPane().setLayout(diag_cons_livLayout);
        diag_cons_livLayout.setHorizontalGroup(
            diag_cons_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_livLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(diag_cons_livLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cons_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cons_liv__but)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        diag_cons_livLayout.setVerticalGroup(
            diag_cons_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_livLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(diag_cons_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cons_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cons_liv__but)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diag_cons_ped.setTitle("Consultar Pedidos");
        diag_cons_ped.setMaximumSize(null);
        diag_cons_ped.setMinimumSize(null);
        diag_cons_ped.setModal(true);
        diag_cons_ped.setResizable(false);

        jLabel47.setText("ID:");

        cons_ped_but.setText("Consultar");
        cons_ped_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_ped_butActionPerformed(evt);
            }
        });

        cons_ped_res.setColumns(20);
        cons_ped_res.setRows(5);
        cons_ped_res.setEnabled(false);
        cons_ped_res.setFocusable(false);
        jScrollPane3.setViewportView(cons_ped_res);

        javax.swing.GroupLayout diag_cons_pedLayout = new javax.swing.GroupLayout(diag_cons_ped.getContentPane());
        diag_cons_ped.getContentPane().setLayout(diag_cons_pedLayout);
        diag_cons_pedLayout.setHorizontalGroup(
            diag_cons_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(diag_cons_pedLayout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cons_ped_id, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cons_ped_but)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diag_cons_pedLayout.setVerticalGroup(
            diag_cons_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addGroup(diag_cons_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cons_ped_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cons_ped_but)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diag_alt_gen.setTitle("Alterar Gênero");
        diag_alt_gen.setMaximumSize(null);
        diag_alt_gen.setMinimumSize(null);
        diag_alt_gen.setModal(true);
        diag_alt_gen.setResizable(false);

        alt_gen_but.setText("Alterar");
        alt_gen_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_gen_butActionPerformed(evt);
            }
        });

        jLabel6.setText("ID:");

        jLabel7.setText("Nova Descrição:");

        javax.swing.GroupLayout diag_alt_genLayout = new javax.swing.GroupLayout(diag_alt_gen.getContentPane());
        diag_alt_gen.getContentPane().setLayout(diag_alt_genLayout);
        diag_alt_genLayout.setHorizontalGroup(
            diag_alt_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_genLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt_gen_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_alt_genLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alt_gen_but)
                .addContainerGap())
        );
        diag_alt_genLayout.setVerticalGroup(
            diag_alt_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_genLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_alt_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alt_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(alt_gen_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt_gen_but)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diag_alt_liv.setTitle("Alterar Livro");
        diag_alt_liv.setMaximumSize(null);
        diag_alt_liv.setMinimumSize(null);
        diag_alt_liv.setModal(true);
        diag_alt_liv.setResizable(false);

        alt_liv_but.setText("Alterar");
        alt_liv_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_liv_butActionPerformed(evt);
            }
        });

        jLabel20.setText("ID:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Novos dados"));

        jLabel35.setText("GENERO_ID:");

        jLabel36.setText("Descrição:");

        jLabel37.setText("Reserva:");

        jLabel38.setText("Preço:");

        jLabel21.setText("Título:");

        jLabel39.setText("Estoque:");

        jLabel32.setText("Autor:");

        jLabel33.setText("Editora:");

        jLabel34.setText("Ano:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_des))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_edi, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_ano))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_aut))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_tit, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_gen, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_pre))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_est, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_res, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(alt_liv_tit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(alt_liv_aut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(alt_liv_edi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(alt_liv_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alt_liv_gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel38)
                    .addComponent(alt_liv_pre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alt_liv_est, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel37)
                    .addComponent(alt_liv_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(alt_liv_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout diag_alt_livLayout = new javax.swing.GroupLayout(diag_alt_liv.getContentPane());
        diag_alt_liv.getContentPane().setLayout(diag_alt_livLayout);
        diag_alt_livLayout.setHorizontalGroup(
            diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_livLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(diag_alt_livLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(alt_liv_but)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diag_alt_livLayout.setVerticalGroup(
            diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_livLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(alt_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt_liv_but)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diag_alt_ped.setTitle("Alterar Pedido");
        diag_alt_ped.setMaximumSize(null);
        diag_alt_ped.setMinimumSize(null);
        diag_alt_ped.setModal(true);
        diag_alt_ped.setResizable(false);

        alt_ped_but.setText("Alterar");
        alt_ped_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_ped_butActionPerformed(evt);
            }
        });

        jLabel49.setText("PEDIDO_ID:");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Novos dados"));

        jLabel50.setText("USUARIO_ID:");

        jLabel55.setText("Data:");

        jLabel56.setText("Pagamento:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt_ped_pag))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt_ped_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt_ped_dat))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(alt_ped_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(alt_ped_dat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alt_ped_pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56)))
        );

        javax.swing.GroupLayout diag_alt_pedLayout = new javax.swing.GroupLayout(diag_alt_ped.getContentPane());
        diag_alt_ped.getContentPane().setLayout(diag_alt_pedLayout);
        diag_alt_pedLayout.setHorizontalGroup(
            diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alt_ped_but)
                    .addGroup(diag_alt_pedLayout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_ped_ped, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diag_alt_pedLayout.setVerticalGroup(
            diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alt_ped_ped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alt_ped_but)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diag_exc_gen.setTitle("Excluir Gênero");
        diag_exc_gen.setMaximumSize(null);
        diag_exc_gen.setMinimumSize(null);
        diag_exc_gen.setModal(true);
        diag_exc_gen.setResizable(false);

        jLabel11.setText("ID:");

        exc_gen_but.setText("Excluir");
        exc_gen_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_gen_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_exc_genLayout = new javax.swing.GroupLayout(diag_exc_gen.getContentPane());
        diag_exc_gen.getContentPane().setLayout(diag_exc_genLayout);
        diag_exc_genLayout.setHorizontalGroup(
            diag_exc_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_genLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_exc_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(diag_exc_genLayout.createSequentialGroup()
                        .addGap(0, 71, Short.MAX_VALUE)
                        .addComponent(exc_gen_but))
                    .addGroup(diag_exc_genLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exc_gen_id)))
                .addContainerGap())
        );
        diag_exc_genLayout.setVerticalGroup(
            diag_exc_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_genLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_exc_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exc_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exc_gen_but)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diag_exc_liv.setTitle("Excluir Livro");
        diag_exc_liv.setMaximumSize(null);
        diag_exc_liv.setMinimumSize(null);
        diag_exc_liv.setModal(true);
        diag_exc_liv.setResizable(false);

        jLabel23.setText("ID:");

        exc_liv_but.setText("Excluir");
        exc_liv_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_liv_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_exc_livLayout = new javax.swing.GroupLayout(diag_exc_liv.getContentPane());
        diag_exc_liv.getContentPane().setLayout(diag_exc_livLayout);
        diag_exc_livLayout.setHorizontalGroup(
            diag_exc_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_livLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_exc_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exc_liv_but)
                    .addGroup(diag_exc_livLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exc_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diag_exc_livLayout.setVerticalGroup(
            diag_exc_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_livLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_exc_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exc_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exc_liv_but)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        diag_exc_ped.setTitle("Excluir Pedido");
        diag_exc_ped.setMaximumSize(null);
        diag_exc_ped.setMinimumSize(null);
        diag_exc_ped.setModal(true);
        diag_exc_ped.setResizable(false);

        jLabel52.setText("ID:");

        exc_ped_but.setText("Exclude");
        exc_ped_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_ped_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_exc_pedLayout = new javax.swing.GroupLayout(diag_exc_ped.getContentPane());
        diag_exc_ped.getContentPane().setLayout(diag_exc_pedLayout);
        diag_exc_pedLayout.setHorizontalGroup(
            diag_exc_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_exc_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exc_ped_but)
                    .addGroup(diag_exc_pedLayout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exc_ped_id, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diag_exc_pedLayout.setVerticalGroup(
            diag_exc_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_exc_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addComponent(exc_ped_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exc_ped_but)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD em JPA");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(190, 193, 199));

        opc_panel.setLayout(new javax.swing.OverlayLayout(opc_panel));

        gen_pan.setBackground(new java.awt.Color(190, 193, 199));

        ins_gen.setText("Inserção");
        ins_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_genActionPerformed(evt);
            }
        });

        alt_gen.setText("Alteração");
        alt_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_genActionPerformed(evt);
            }
        });

        exc_gen.setText("Exclusão");
        exc_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_genActionPerformed(evt);
            }
        });

        cons_gen.setText("Consulta");
        cons_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_genActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gen_panLayout = new javax.swing.GroupLayout(gen_pan);
        gen_pan.setLayout(gen_panLayout);
        gen_panLayout.setHorizontalGroup(
            gen_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ins_gen, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(alt_gen)
            .addComponent(exc_gen, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cons_gen, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        gen_panLayout.setVerticalGroup(
            gen_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gen_panLayout.createSequentialGroup()
                .addComponent(ins_gen)
                .addGap(7, 7, 7)
                .addComponent(alt_gen)
                .addGap(7, 7, 7)
                .addComponent(exc_gen)
                .addGap(7, 7, 7)
                .addComponent(cons_gen))
        );

        opc_panel.setLayer(gen_pan, 1);
        opc_panel.add(gen_pan);

        liv_pan.setBackground(new java.awt.Color(190, 193, 199));

        ins_liv.setText("Inserção");
        ins_liv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_livActionPerformed(evt);
            }
        });

        alt_liv.setText("Alteração");
        alt_liv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_livActionPerformed(evt);
            }
        });

        exc_liv.setText("Exclusão");
        exc_liv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_livActionPerformed(evt);
            }
        });

        cons_liv.setText("Consulta");
        cons_liv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_livActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout liv_panLayout = new javax.swing.GroupLayout(liv_pan);
        liv_pan.setLayout(liv_panLayout);
        liv_panLayout.setHorizontalGroup(
            liv_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ins_liv, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(alt_liv)
            .addComponent(exc_liv, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cons_liv, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        liv_panLayout.setVerticalGroup(
            liv_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(liv_panLayout.createSequentialGroup()
                .addComponent(ins_liv)
                .addGap(7, 7, 7)
                .addComponent(alt_liv)
                .addGap(7, 7, 7)
                .addComponent(exc_liv)
                .addGap(7, 7, 7)
                .addComponent(cons_liv))
        );

        opc_panel.add(liv_pan);

        ped_pan.setBackground(new java.awt.Color(190, 193, 199));

        ins_ped.setText("Inserção");
        ins_ped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_pedActionPerformed(evt);
            }
        });

        alt_ped.setText("Alteração");
        alt_ped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_pedActionPerformed(evt);
            }
        });

        exc_ped.setText("Exclusão");
        exc_ped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_pedActionPerformed(evt);
            }
        });

        cons_ped.setText("Consulta");
        cons_ped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_pedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ped_panLayout = new javax.swing.GroupLayout(ped_pan);
        ped_pan.setLayout(ped_panLayout);
        ped_panLayout.setHorizontalGroup(
            ped_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ins_ped, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(alt_ped)
            .addComponent(exc_ped, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(cons_ped, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ped_panLayout.setVerticalGroup(
            ped_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ped_panLayout.createSequentialGroup()
                .addComponent(ins_ped)
                .addGap(7, 7, 7)
                .addComponent(alt_ped)
                .addGap(7, 7, 7)
                .addComponent(exc_ped)
                .addGap(7, 7, 7)
                .addComponent(cons_ped))
        );

        opc_panel.add(ped_pan);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        butg_Tabelas.add(ped_but);
        ped_but.setText("Pedido");
        ped_but.setFocusPainted(false);
        ped_but.setFocusable(false);
        ped_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ped_butActionPerformed(evt);
            }
        });

        butg_Tabelas.add(liv_but);
        liv_but.setText("Livro");
        liv_but.setFocusPainted(false);
        liv_but.setFocusable(false);
        liv_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liv_butActionPerformed(evt);
            }
        });

        butg_Tabelas.add(gen_but);
        gen_but.setSelected(true);
        gen_but.setText("Gêneros");
        gen_but.setFocusPainted(false);
        gen_but.setFocusable(false);
        gen_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gen_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gen_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(liv_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ped_but, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(gen_but, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(liv_but, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ped_but, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(opc_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opc_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ins_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_genActionPerformed
        // TODO add your handling code here:
        diag_ins_gen.pack();
        diag_ins_gen.setLocationRelativeTo(null);
        diag_ins_gen.setVisible(true);

    }//GEN-LAST:event_ins_genActionPerformed

    private void ins_gen_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_gen_butActionPerformed
        try {
            Generos genero = new Generos();

            genero.setGENERO_ID(Integer.parseInt(ins_gen_id.getText()));
            genero.setDESCRICAO(ins_gen_desc.getText());

            em.getTransaction().begin();
            em.persist(genero);
            em.getTransaction().commit();

            diag_ins_gen.pack();
            diag_ins_gen.setLocationRelativeTo(null);
            diag_ins_gen.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_ins_gen_butActionPerformed

    private void cons_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_genActionPerformed
        diag_cons_gen.pack();
        diag_cons_gen.setLocationRelativeTo(null);
        diag_cons_gen.setVisible(true);
    }//GEN-LAST:event_cons_genActionPerformed

    private void cons_gen_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_gen_butActionPerformed
        try {
            Generos genero = em.find(Generos.class, Integer.parseInt(cons_gen_id.getText()));
            cons_gen_res.setText(genero.getDESCRICAO());
            //findGenero.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cons_gen_butActionPerformed

    private void alt_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_genActionPerformed
        diag_alt_gen.pack();
        diag_alt_gen.setLocationRelativeTo(null);
        diag_alt_gen.setVisible(true);
    }//GEN-LAST:event_alt_genActionPerformed

    private void alt_gen_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_gen_butActionPerformed
        try {
            Generos genero = em.find(Generos.class, Integer.parseInt(alt_gen_id.getText()));

            em.getTransaction().begin();
            genero.setDESCRICAO(alt_gen_desc.getText());
            em.getTransaction().commit();

            diag_alt_gen.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_alt_gen_butActionPerformed

    private void exc_gen_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_gen_butActionPerformed
        try {
            Generos genero = em.find(Generos.class, Integer.parseInt(exc_gen_id.getText()));
            em.getTransaction().begin();
            em.remove(genero);
            em.getTransaction().commit();

            diag_exc_gen.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_exc_gen_butActionPerformed

    private void exc_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_genActionPerformed
        diag_exc_gen.pack();
        diag_exc_gen.setLocationRelativeTo(null);
        diag_exc_gen.setVisible(true);
    }//GEN-LAST:event_exc_genActionPerformed

    private void cons_livActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_livActionPerformed
        diag_cons_liv.pack();
        diag_cons_liv.setLocationRelativeTo(null);
        diag_cons_liv.setVisible(true);
    }//GEN-LAST:event_cons_livActionPerformed

    private void exc_livActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_livActionPerformed
        diag_exc_liv.pack();
        diag_exc_liv.setLocationRelativeTo(null);
        diag_exc_liv.setVisible(true);
    }//GEN-LAST:event_exc_livActionPerformed

    private void alt_livActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_livActionPerformed
        diag_alt_liv.pack();
        diag_alt_liv.setLocationRelativeTo(null);
        diag_alt_liv.setVisible(true);
    }//GEN-LAST:event_alt_livActionPerformed

    private void ins_livActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_livActionPerformed
        diag_ins_liv.pack();
        diag_ins_liv.setLocationRelativeTo(null);
        diag_ins_liv.setVisible(true);
    }//GEN-LAST:event_ins_livActionPerformed

    private void cons_pedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_pedActionPerformed
        diag_cons_ped.pack();
        diag_cons_ped.setLocationRelativeTo(null);
        diag_cons_ped.setVisible(true);
    }//GEN-LAST:event_cons_pedActionPerformed

    private void exc_pedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_pedActionPerformed
        diag_exc_ped.pack();
        diag_exc_ped.setLocationRelativeTo(null);
        diag_exc_ped.setVisible(true);
    }//GEN-LAST:event_exc_pedActionPerformed

    private void alt_pedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_pedActionPerformed
        diag_alt_ped.pack();
        diag_alt_ped.setLocationRelativeTo(null);
        diag_alt_ped.setVisible(true);
    }//GEN-LAST:event_alt_pedActionPerformed

    private void ins_pedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_pedActionPerformed
        diag_ins_ped.pack();
        diag_ins_ped.setLocationRelativeTo(null);
        diag_ins_ped.setVisible(true);
    }//GEN-LAST:event_ins_pedActionPerformed

    private void ins_liv_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_liv_butActionPerformed
        try {
            Livros livro = new Livros();

            livro.setLIVRO_ID(Integer.parseInt(ins_liv_id.getText()));
            livro.setTITULO(ins_liv_tit.getText());
            livro.setAUTOR(ins_liv_aut.getText());
            livro.setEDITORA(ins_liv_edi.getText());
            livro.setANO(Integer.parseInt(ins_liv_ano.getText()));
            livro.setGENERO_ID(Integer.parseInt(ins_liv_gen.getText()));
            livro.setDESCRICAO(ins_liv_des.getText());
            livro.setPRECO(Double.parseDouble(ins_liv_pre.getText()));
            livro.setESTOQUE(Integer.parseInt(ins_liv_est.getText()));
            livro.setRESERVA(Integer.parseInt(ins_liv_res.getText()));

            em.getTransaction().begin();
            em.persist(livro);
            em.getTransaction().commit();

            diag_ins_liv.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_ins_liv_butActionPerformed

    private void cons_liv__butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_liv__butActionPerformed
        try {
            Livros livro = em.find(Livros.class, Integer.parseInt(cons_liv_id.getText()));
            cons_liv_res.setText(livro.toString());
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cons_liv__butActionPerformed

    private void alt_liv_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_liv_butActionPerformed
        try {
            Livros livros = em.find(Livros.class, Integer.parseInt(alt_liv_id.getText()));

            em.getTransaction().begin();
            livros.setTITULO(alt_liv_tit.getText());
            livros.setAUTOR(alt_liv_aut.getText());
            livros.setEDITORA(alt_liv_edi.getText());
            livros.setANO(Integer.parseInt(alt_liv_ano.getText()));
            livros.setGENERO_ID(Integer.parseInt(alt_liv_gen.getText()));
            livros.setDESCRICAO(alt_liv_des.getText());
            livros.setPRECO(Double.parseDouble(alt_liv_pre.getText()));
            livros.setESTOQUE(Integer.parseInt(alt_liv_est.getText()));
            livros.setRESERVA(Integer.parseInt(alt_liv_res.getText()));
            em.getTransaction().commit();

            diag_alt_liv.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_alt_liv_butActionPerformed

    private void exc_liv_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_liv_butActionPerformed
        try {
            Livros livro = em.find(Livros.class, Integer.parseInt(exc_liv_id.getText()));
            em.getTransaction().begin();
            em.remove(livro);
            em.getTransaction().commit();

            diag_exc_liv.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_exc_liv_butActionPerformed

    private void ins_liv_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_liv_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_liv_genActionPerformed

    private void ins_ped_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_ped_butActionPerformed
        try {
            Pedidos pedido = new Pedidos();

            pedido.setPEDIDO_ID(Integer.parseInt(ins_ped_ped.getText()));
            pedido.setUSUARIO_ID(Integer.parseInt(ins_ped_usu.getText()));
            pedido.setDATA_PEDIDO(ins_ped_dat.getText());
            pedido.setTIPO_PAG(ins_ped_pag.getText());

            em.getTransaction().begin();
            em.persist(pedido);
            em.getTransaction().commit();

            diag_ins_ped.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_ins_ped_butActionPerformed

    private void cons_ped_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_ped_butActionPerformed
        try {
            Pedidos pedido = em.find(Pedidos.class, Integer.parseInt(cons_ped_id.getText()));
            cons_ped_res.setText(pedido.toString());
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_cons_ped_butActionPerformed

    private void alt_ped_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_ped_butActionPerformed
        try {
            Pedidos pedido = em.find(Pedidos.class, Integer.parseInt(alt_ped_ped.getText()));

            em.getTransaction().begin();

            pedido.setUSUARIO_ID(Integer.parseInt(alt_ped_usu.getText()));
            pedido.setDATA_PEDIDO(alt_ped_dat.getText());
            pedido.setTIPO_PAG(alt_ped_pag.getText());

            em.getTransaction().commit();

            diag_alt_ped.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_alt_ped_butActionPerformed

    private void exc_ped_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_ped_butActionPerformed
        try {
            Pedidos pedido = em.find(Pedidos.class, Integer.parseInt(exc_ped_id.getText()));
            em.getTransaction().begin();
            em.remove(pedido);
            em.getTransaction().commit();

            diag_exc_ped.setVisible(false);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_exc_ped_butActionPerformed

    private void ins_ped_datActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_ped_datActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_ped_datActionPerformed

    private void liv_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liv_butActionPerformed
        trocaTela(liv_pan);
    }//GEN-LAST:event_liv_butActionPerformed

    private void gen_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gen_butActionPerformed
        trocaTela(gen_pan);
    }//GEN-LAST:event_gen_butActionPerformed

    private void ped_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ped_butActionPerformed
        trocaTela(ped_pan);
    }//GEN-LAST:event_ped_butActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Janela janela = new Janela();
                janela.setLocationRelativeTo(null);
                janela.setVisible(true);

            }

        });
    }

    public Generos findGeneros(int id) {
        Generos genero = em.find(Generos.class, id);
        return genero;
    }

    public void finalize() {
        em.close();
        emf.close();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alt_gen;
    private javax.swing.JButton alt_gen_but;
    private javax.swing.JTextField alt_gen_desc;
    private javax.swing.JTextField alt_gen_id;
    private javax.swing.JButton alt_liv;
    private javax.swing.JTextField alt_liv_ano;
    private javax.swing.JTextField alt_liv_aut;
    private javax.swing.JButton alt_liv_but;
    private javax.swing.JTextField alt_liv_des;
    private javax.swing.JTextField alt_liv_edi;
    private javax.swing.JTextField alt_liv_est;
    private javax.swing.JTextField alt_liv_gen;
    private javax.swing.JTextField alt_liv_id;
    private javax.swing.JTextField alt_liv_pre;
    private javax.swing.JTextField alt_liv_res;
    private javax.swing.JTextField alt_liv_tit;
    private javax.swing.JButton alt_ped;
    private javax.swing.JButton alt_ped_but;
    private javax.swing.JTextField alt_ped_dat;
    private javax.swing.JTextField alt_ped_pag;
    private javax.swing.JTextField alt_ped_ped;
    private javax.swing.JTextField alt_ped_usu;
    private javax.swing.ButtonGroup butg_Tabelas;
    private javax.swing.JButton cons_gen;
    private javax.swing.JButton cons_gen_but;
    private javax.swing.JTextField cons_gen_id;
    private javax.swing.JTextArea cons_gen_res;
    private javax.swing.JButton cons_liv;
    private javax.swing.JButton cons_liv__but;
    private javax.swing.JTextField cons_liv_id;
    private javax.swing.JTextArea cons_liv_res;
    private javax.swing.JButton cons_ped;
    private javax.swing.JButton cons_ped_but;
    private javax.swing.JTextField cons_ped_id;
    private javax.swing.JTextArea cons_ped_res;
    private javax.swing.JDialog diag_alt_gen;
    private javax.swing.JDialog diag_alt_liv;
    private javax.swing.JDialog diag_alt_ped;
    private javax.swing.JDialog diag_cons_gen;
    private javax.swing.JDialog diag_cons_liv;
    private javax.swing.JDialog diag_cons_ped;
    private javax.swing.JDialog diag_exc_gen;
    private javax.swing.JDialog diag_exc_liv;
    private javax.swing.JDialog diag_exc_ped;
    private javax.swing.JDialog diag_ins_gen;
    private javax.swing.JDialog diag_ins_liv;
    private javax.swing.JDialog diag_ins_ped;
    private javax.swing.JButton exc_gen;
    private javax.swing.JButton exc_gen_but;
    private javax.swing.JTextField exc_gen_id;
    private javax.swing.JButton exc_liv;
    private javax.swing.JButton exc_liv_but;
    private javax.swing.JTextField exc_liv_id;
    private javax.swing.JButton exc_ped;
    private javax.swing.JButton exc_ped_but;
    private javax.swing.JTextField exc_ped_id;
    private javax.swing.JToggleButton gen_but;
    private javax.swing.JPanel gen_pan;
    private javax.swing.JButton ins_gen;
    private javax.swing.JButton ins_gen_but;
    private javax.swing.JTextField ins_gen_desc;
    private javax.swing.JTextField ins_gen_id;
    private javax.swing.JButton ins_liv;
    private javax.swing.JTextField ins_liv_ano;
    private javax.swing.JTextField ins_liv_aut;
    private javax.swing.JButton ins_liv_but;
    private javax.swing.JTextField ins_liv_des;
    private javax.swing.JTextField ins_liv_edi;
    private javax.swing.JTextField ins_liv_est;
    private javax.swing.JTextField ins_liv_gen;
    private javax.swing.JTextField ins_liv_id;
    private javax.swing.JTextField ins_liv_pre;
    private javax.swing.JTextField ins_liv_res;
    private javax.swing.JTextField ins_liv_tit;
    private javax.swing.JButton ins_ped;
    private javax.swing.JButton ins_ped_but;
    private javax.swing.JTextField ins_ped_dat;
    private javax.swing.JTextField ins_ped_pag;
    private javax.swing.JTextField ins_ped_ped;
    private javax.swing.JTextField ins_ped_usu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton liv_but;
    private javax.swing.JPanel liv_pan;
    private javax.swing.JLayeredPane opc_panel;
    private javax.swing.JToggleButton ped_but;
    private javax.swing.JPanel ped_pan;
    // End of variables declaration//GEN-END:variables
}
