/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbcrud;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import tabelas.*;

/**
 * @author Tomás Abril
 * @author Daniel Silva Curi
 */
public class Janela extends javax.swing.JFrame {

    EntityManagerFactory emf;
    EntityManager em;

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();

        //fazer conexao com o banco de dados
        emf = Persistence.createEntityManagerFactory("DbCRUDPU");
        em = emf.createEntityManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diag_ins_gen = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        ins_gen_but = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        ins_gen_desc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ins_gen_id = new javax.swing.JTextField();
        diag_ins_liv = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        ins_liv_but = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ins_liv_edi = new javax.swing.JTextField();
        ins_liv_id = new javax.swing.JTextField();
        ins_liv_gen = new javax.swing.JTextField();
        ins_liv_ano = new javax.swing.JTextField();
        ins_liv_pre = new javax.swing.JTextField();
        ins_liv_des = new javax.swing.JTextField();
        ins_liv_res = new javax.swing.JTextField();
        ins_liv_est = new javax.swing.JTextField();
        ins_liv_aut = new javax.swing.JTextField();
        ins_liv_tit = new javax.swing.JTextField();
        diag_ins_ped = new javax.swing.JDialog();
        jLabel43 = new javax.swing.JLabel();
        ins_ped_but = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        ins_ped_usu = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        ins_ped_ped = new javax.swing.JTextField();
        ins_ped_dat = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        ins_ped_pag = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        diag_cons_gen = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cons_gen_id = new javax.swing.JTextField();
        cons_gen_but = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cons_gen_res = new javax.swing.JTextArea();
        diag_cons_liv = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cons_liv_id = new javax.swing.JTextField();
        cons_liv__but = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cons_liv_res = new javax.swing.JTextArea();
        diag_cons_ped = new javax.swing.JDialog();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        cons_ped_id = new javax.swing.JTextField();
        cons_ped_but = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        cons_ped_res = new javax.swing.JTextArea();
        diag_alt_gen = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        alt_gen_but = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        alt_gen_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        alt_gen_desc = new javax.swing.JTextField();
        diag_alt_liv = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        alt_liv_but = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        alt_liv_id = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        alt_liv_tit = new javax.swing.JTextField();
        alt_liv_aut = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        alt_liv_edi = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        alt_liv_ano = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        alt_liv_gen = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        alt_liv_des = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        alt_liv_res = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        alt_liv_pre = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        alt_liv_est = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        diag_alt_ped = new javax.swing.JDialog();
        jLabel48 = new javax.swing.JLabel();
        alt_ped_but = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        alt_ped_ped = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        alt_ped_usu = new javax.swing.JTextField();
        alt_ped_dat = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        alt_ped_pag = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        diag_exc_gen = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        exc_gen_id = new javax.swing.JTextField();
        exc_gen_but = new javax.swing.JButton();
        diag_exc_liv = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        exc_liv_id = new javax.swing.JTextField();
        exc_liv_but = new javax.swing.JButton();
        diag_exc_ped = new javax.swing.JDialog();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        exc_ped_id = new javax.swing.JTextField();
        exc_ped_but = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        ins_gen = new javax.swing.JButton();
        alt_gen = new javax.swing.JButton();
        exc_gen = new javax.swing.JButton();
        cons_gen = new javax.swing.JButton();
        lab_gen = new javax.swing.JLabel();
        lab_liv = new javax.swing.JLabel();
        cons_liv = new javax.swing.JButton();
        exc_liv = new javax.swing.JButton();
        alt_liv = new javax.swing.JButton();
        ins_liv = new javax.swing.JButton();
        lab_ped = new javax.swing.JLabel();
        cons_ped = new javax.swing.JButton();
        exc_ped = new javax.swing.JButton();
        alt_ped = new javax.swing.JButton();
        ins_ped = new javax.swing.JButton();

        diag_ins_gen.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel8.setText("Genero");

        ins_gen_but.setText("inserir");
        ins_gen_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_gen_butActionPerformed(evt);
            }
        });

        jLabel10.setText("Descrição:");

        jLabel3.setText("id:");

        javax.swing.GroupLayout diag_ins_genLayout = new javax.swing.GroupLayout(diag_ins_gen.getContentPane());
        diag_ins_gen.getContentPane().setLayout(diag_ins_genLayout);
        diag_ins_genLayout.setHorizontalGroup(
            diag_ins_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ins_genLayout.createSequentialGroup()
                .addGroup(diag_ins_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_ins_genLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(diag_ins_genLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(ins_gen_but))
                    .addGroup(diag_ins_genLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(diag_ins_genLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(diag_ins_genLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(diag_ins_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ins_gen_id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ins_gen_desc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        diag_ins_genLayout.setVerticalGroup(
            diag_ins_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ins_genLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ins_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ins_gen_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(ins_gen_but)
                .addContainerGap())
        );

        diag_ins_liv.setMinimumSize(new java.awt.Dimension(400, 600));

        jLabel14.setText("inserir livro");

        ins_liv_but.setText("inserir");
        ins_liv_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_liv_butActionPerformed(evt);
            }
        });

        jLabel15.setText("titulo:");

        jLabel16.setText("id:");

        jLabel24.setText("autor");

        jLabel25.setText("editora");

        jLabel26.setText("ano");

        jLabel27.setText("GENERO_ID");

        jLabel28.setText("descricao");

        jLabel29.setText("preco");

        jLabel30.setText("reserva");

        jLabel31.setText("estoque");

        ins_liv_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_liv_genActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_ins_livLayout = new javax.swing.GroupLayout(diag_ins_liv.getContentPane());
        diag_ins_liv.getContentPane().setLayout(diag_ins_livLayout);
        diag_ins_livLayout.setHorizontalGroup(
            diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ins_livLayout.createSequentialGroup()
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(ins_liv_but))
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ins_liv_id, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                .addGap(169, 169, 169))
            .addGroup(diag_ins_livLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_aut, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_edi))
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_ano, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_gen))
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_des, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_pre))
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_est, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_res))
                    .addGroup(diag_ins_livLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_liv_tit, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                .addGap(159, 159, 159))
        );
        diag_ins_livLayout.setVerticalGroup(
            diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ins_livLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(9, 9, 9)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ins_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ins_liv_tit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(ins_liv_aut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(ins_liv_edi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(ins_liv_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27)
                    .addComponent(ins_liv_gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(ins_liv_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_ins_livLayout.createSequentialGroup()
                        .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(ins_liv_pre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel31))
                    .addComponent(ins_liv_est, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_ins_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ins_liv_res, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(ins_liv_but)
                .addContainerGap())
        );

        diag_ins_ped.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel43.setText("Genero");

        ins_ped_but.setText("inserir");
        ins_ped_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_ped_butActionPerformed(evt);
            }
        });

        jLabel44.setText("USUARIO_ID");

        jLabel45.setText("PEDIDO_ID");

        ins_ped_dat.setText("2008-7-04");
        ins_ped_dat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_ped_datActionPerformed(evt);
            }
        });

        jLabel53.setText("data pedido(tipo mysql DATE)");

        jLabel54.setText("tipo pagamento(small int)");

        javax.swing.GroupLayout diag_ins_pedLayout = new javax.swing.GroupLayout(diag_ins_ped.getContentPane());
        diag_ins_ped.getContentPane().setLayout(diag_ins_pedLayout);
        diag_ins_pedLayout.setHorizontalGroup(
            diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ins_pedLayout.createSequentialGroup()
                .addGroup(diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_ins_pedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel43))
                    .addGroup(diag_ins_pedLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(ins_ped_but))
                    .addGroup(diag_ins_pedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_ped_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diag_ins_pedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_ped_ped, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diag_ins_pedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_ped_dat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diag_ins_pedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_ped_pag, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        diag_ins_pedLayout.setVerticalGroup(
            diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_ins_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addGap(27, 27, 27)
                .addGroup(diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(ins_ped_ped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(ins_ped_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(ins_ped_dat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_ins_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(ins_ped_pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(ins_ped_but)
                .addContainerGap())
        );

        diag_cons_gen.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel2.setText("Find:");

        jLabel4.setText("ID");

        cons_gen_but.setText("Find");
        cons_gen_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_gen_butActionPerformed(evt);
            }
        });

        cons_gen_res.setColumns(20);
        cons_gen_res.setRows(5);
        jScrollPane1.setViewportView(cons_gen_res);

        javax.swing.GroupLayout diag_cons_genLayout = new javax.swing.GroupLayout(diag_cons_gen.getContentPane());
        diag_cons_gen.getContentPane().setLayout(diag_cons_genLayout);
        diag_cons_genLayout.setHorizontalGroup(
            diag_cons_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_genLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(cons_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_cons_genLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cons_gen_but)
                .addGap(169, 169, 169))
        );
        diag_cons_genLayout.setVerticalGroup(
            diag_cons_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_genLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_cons_genLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cons_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(cons_gen_but)
                .addContainerGap())
        );

        diag_cons_liv.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel17.setText("Find:");

        jLabel18.setText("ID");

        cons_liv__but.setText("Find");
        cons_liv__but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_liv__butActionPerformed(evt);
            }
        });

        cons_liv_res.setColumns(20);
        cons_liv_res.setRows(5);
        jScrollPane2.setViewportView(cons_liv_res);

        javax.swing.GroupLayout diag_cons_livLayout = new javax.swing.GroupLayout(diag_cons_liv.getContentPane());
        diag_cons_liv.getContentPane().setLayout(diag_cons_livLayout);
        diag_cons_livLayout.setHorizontalGroup(
            diag_cons_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_livLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(cons_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_cons_livLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cons_liv__but)
                .addGap(169, 169, 169))
        );
        diag_cons_livLayout.setVerticalGroup(
            diag_cons_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_livLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_cons_livLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cons_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(cons_liv__but)
                .addContainerGap())
        );

        diag_cons_ped.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel46.setText("Find:");

        jLabel47.setText("ID");

        cons_ped_but.setText("Find");
        cons_ped_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_ped_butActionPerformed(evt);
            }
        });

        cons_ped_res.setColumns(20);
        cons_ped_res.setRows(5);
        jScrollPane3.setViewportView(cons_ped_res);

        javax.swing.GroupLayout diag_cons_pedLayout = new javax.swing.GroupLayout(diag_cons_ped.getContentPane());
        diag_cons_ped.getContentPane().setLayout(diag_cons_pedLayout);
        diag_cons_pedLayout.setHorizontalGroup(
            diag_cons_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addComponent(cons_ped_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_cons_pedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cons_ped_but)
                .addGap(169, 169, 169))
        );
        diag_cons_pedLayout.setVerticalGroup(
            diag_cons_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_cons_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_cons_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_cons_pedLayout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cons_ped_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(cons_ped_but)
                .addContainerGap())
        );

        diag_alt_gen.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel5.setText("alter genero");

        alt_gen_but.setText("Alter");
        alt_gen_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_gen_butActionPerformed(evt);
            }
        });

        jLabel6.setText("id do campo para alterar");

        jLabel7.setText("nova descricao");

        javax.swing.GroupLayout diag_alt_genLayout = new javax.swing.GroupLayout(diag_alt_gen.getContentPane());
        diag_alt_gen.getContentPane().setLayout(diag_alt_genLayout);
        diag_alt_genLayout.setHorizontalGroup(
            diag_alt_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_genLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_alt_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(diag_alt_genLayout.createSequentialGroup()
                        .addGroup(diag_alt_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alt_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(30, 30, 30)
                        .addGroup(diag_alt_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(alt_gen_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alt_gen_but))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        diag_alt_genLayout.setVerticalGroup(
            diag_alt_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_genLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(diag_alt_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diag_alt_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alt_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alt_gen_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(alt_gen_but)
                .addContainerGap())
        );

        diag_alt_liv.setMinimumSize(new java.awt.Dimension(400, 600));

        jLabel19.setText("alter livro");

        alt_liv_but.setText("Alter");
        alt_liv_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_liv_butActionPerformed(evt);
            }
        });

        jLabel20.setText("id do objeto a ser alterado");

        jLabel21.setText("novo titulo");

        jLabel32.setText("novo autor");

        jLabel33.setText("nova editora");

        jLabel34.setText("novo ano");

        jLabel35.setText("novo GENERO_ID");

        jLabel36.setText("nova descricao");

        jLabel37.setText("nova reserva");

        jLabel38.setText("novo preco");

        jLabel39.setText("novo estoque");

        javax.swing.GroupLayout diag_alt_livLayout = new javax.swing.GroupLayout(diag_alt_liv.getContentPane());
        diag_alt_liv.getContentPane().setLayout(diag_alt_livLayout);
        diag_alt_livLayout.setHorizontalGroup(
            diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_livLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_alt_livLayout.createSequentialGroup()
                        .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19)
                            .addGroup(diag_alt_livLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(alt_liv_but))
                            .addGroup(diag_alt_livLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alt_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(diag_alt_livLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alt_liv_tit)))
                        .addGap(0, 149, Short.MAX_VALUE))
                    .addGroup(diag_alt_livLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_aut))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_alt_livLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_edi))
                    .addGroup(diag_alt_livLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_ano))
                    .addGroup(diag_alt_livLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_gen))
                    .addGroup(diag_alt_livLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_des))
                    .addGroup(diag_alt_livLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_res))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diag_alt_livLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_pre))
                    .addGroup(diag_alt_livLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alt_liv_est)))
                .addContainerGap())
        );
        diag_alt_livLayout.setVerticalGroup(
            diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_livLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(alt_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(alt_liv_tit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(alt_liv_aut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(alt_liv_edi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(alt_liv_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(alt_liv_gen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(alt_liv_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(alt_liv_pre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(alt_liv_est, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diag_alt_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(alt_liv_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(alt_liv_but)
                .addContainerGap())
        );

        diag_alt_ped.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel48.setText("alter pedido");

        alt_ped_but.setText("Alter");
        alt_ped_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_ped_butActionPerformed(evt);
            }
        });

        jLabel49.setText("PEDIDO_ID do campo para alterar");

        jLabel50.setText("USUARIO_ID");

        jLabel55.setText("data pedido");

        jLabel56.setText("tipo pagamento(string)");

        javax.swing.GroupLayout diag_alt_pedLayout = new javax.swing.GroupLayout(diag_alt_ped.getContentPane());
        diag_alt_ped.getContentPane().setLayout(diag_alt_pedLayout);
        diag_alt_pedLayout.setHorizontalGroup(
            diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48)
                    .addGroup(diag_alt_pedLayout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addGroup(diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(diag_alt_pedLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(alt_ped_but))
                            .addGroup(diag_alt_pedLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(alt_ped_ped, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(diag_alt_pedLayout.createSequentialGroup()
                        .addComponent(jLabel50)
                        .addGap(18, 18, 18)
                        .addComponent(alt_ped_usu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diag_alt_pedLayout.createSequentialGroup()
                        .addComponent(jLabel55)
                        .addGap(18, 18, 18)
                        .addComponent(alt_ped_dat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diag_alt_pedLayout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addGap(18, 18, 18)
                        .addComponent(alt_ped_pag, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        diag_alt_pedLayout.setVerticalGroup(
            diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_alt_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel48)
                .addGap(18, 18, 18)
                .addGroup(diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(alt_ped_ped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(alt_ped_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(alt_ped_dat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diag_alt_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(alt_ped_pag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(alt_ped_but)
                .addContainerGap())
        );

        diag_exc_gen.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel9.setText("Exclude Genero");

        jLabel11.setText("ID do objeto a ser excluido:");

        exc_gen_but.setText("Exclude");
        exc_gen_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_gen_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_exc_genLayout = new javax.swing.GroupLayout(diag_exc_gen.getContentPane());
        diag_exc_gen.getContentPane().setLayout(diag_exc_genLayout);
        diag_exc_genLayout.setHorizontalGroup(
            diag_exc_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_genLayout.createSequentialGroup()
                .addGroup(diag_exc_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_exc_genLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(diag_exc_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(exc_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(diag_exc_genLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(exc_gen_but)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        diag_exc_genLayout.setVerticalGroup(
            diag_exc_genLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_genLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exc_gen_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(exc_gen_but)
                .addGap(19, 19, 19))
        );

        diag_exc_liv.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel22.setText("Exclude Livro");

        jLabel23.setText("ID do objeto a ser excluido:");

        exc_liv_but.setText("Exclude");
        exc_liv_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_liv_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_exc_livLayout = new javax.swing.GroupLayout(diag_exc_liv.getContentPane());
        diag_exc_liv.getContentPane().setLayout(diag_exc_livLayout);
        diag_exc_livLayout.setHorizontalGroup(
            diag_exc_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_livLayout.createSequentialGroup()
                .addGroup(diag_exc_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_exc_livLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(diag_exc_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(exc_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(diag_exc_livLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(exc_liv_but)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        diag_exc_livLayout.setVerticalGroup(
            diag_exc_livLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_livLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exc_liv_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(exc_liv_but)
                .addGap(19, 19, 19))
        );

        diag_exc_ped.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel51.setText("Exclude Pedido");

        jLabel52.setText("ID do objeto a ser excluido:");

        exc_ped_but.setText("Exclude");
        exc_ped_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_ped_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diag_exc_pedLayout = new javax.swing.GroupLayout(diag_exc_ped.getContentPane());
        diag_exc_ped.getContentPane().setLayout(diag_exc_pedLayout);
        diag_exc_pedLayout.setHorizontalGroup(
            diag_exc_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_pedLayout.createSequentialGroup()
                .addGroup(diag_exc_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diag_exc_pedLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(diag_exc_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addComponent(exc_ped_id, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(diag_exc_pedLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(exc_ped_but)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        diag_exc_pedLayout.setVerticalGroup(
            diag_exc_pedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diag_exc_pedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addGap(18, 18, 18)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exc_ped_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(exc_ped_but)
                .addGap(19, 19, 19))
        );

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Gêneros", "Livro", "Pedido" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane4.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD em JPA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ins_gen.setText("Inserção");
        ins_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_genActionPerformed(evt);
            }
        });
        getContentPane().add(ins_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 79, -1));

        alt_gen.setText("Alteração");
        alt_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_genActionPerformed(evt);
            }
        });
        getContentPane().add(alt_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        exc_gen.setText("Exclusão");
        exc_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_genActionPerformed(evt);
            }
        });
        getContentPane().add(exc_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 79, -1));

        cons_gen.setText("Consulta");
        cons_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_genActionPerformed(evt);
            }
        });
        getContentPane().add(cons_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 79, -1));

        lab_gen.setText("Generos:");
        getContentPane().add(lab_gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 79, -1));

        lab_liv.setText("Livro:");
        getContentPane().add(lab_liv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 79, -1));

        cons_liv.setText("Consulta");
        cons_liv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_livActionPerformed(evt);
            }
        });
        getContentPane().add(cons_liv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 79, -1));

        exc_liv.setText("Exclusão");
        exc_liv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_livActionPerformed(evt);
            }
        });
        getContentPane().add(exc_liv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 79, -1));

        alt_liv.setText("Alteração");
        alt_liv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_livActionPerformed(evt);
            }
        });
        getContentPane().add(alt_liv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        ins_liv.setText("Inserção");
        ins_liv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_livActionPerformed(evt);
            }
        });
        getContentPane().add(ins_liv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 79, -1));

        lab_ped.setText("Pedido:");
        getContentPane().add(lab_ped, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 79, -1));

        cons_ped.setText("Consulta");
        cons_ped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_pedActionPerformed(evt);
            }
        });
        getContentPane().add(cons_ped, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 79, -1));

        exc_ped.setText("Exclusão");
        exc_ped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exc_pedActionPerformed(evt);
            }
        });
        getContentPane().add(exc_ped, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 79, -1));

        alt_ped.setText("Alteração");
        alt_ped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alt_pedActionPerformed(evt);
            }
        });
        getContentPane().add(alt_ped, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        ins_ped.setText("Inserção");
        ins_ped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_pedActionPerformed(evt);
            }
        });
        getContentPane().add(ins_ped, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 79, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ins_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_genActionPerformed
        // TODO add your handling code here:
        diag_ins_gen.setVisible(true);
    }//GEN-LAST:event_ins_genActionPerformed

    private void ins_gen_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_gen_butActionPerformed
        Generos genero = new Generos();
        
        genero.setGENERO_ID(Integer.parseInt(ins_gen_id.getText()));
        genero.setDESCRICAO(ins_gen_desc.getText());
        
        em.getTransaction().begin();
        em.persist(genero);
        em.getTransaction().commit();
        
        diag_ins_gen.setVisible(false);
    }//GEN-LAST:event_ins_gen_butActionPerformed

    private void cons_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_genActionPerformed
        // TODO add your handling code here:
        //consulta
        diag_cons_gen.setVisible(true);
    }//GEN-LAST:event_cons_genActionPerformed

    private void cons_gen_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_gen_butActionPerformed
        Generos genero = em.find(Generos.class, Integer.parseInt(cons_gen_id.getText()));
        cons_gen_res.setText(genero.getDESCRICAO());
        //findGenero.setVisible(false);
    }//GEN-LAST:event_cons_gen_butActionPerformed

    private void alt_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_genActionPerformed
        // TODO add your handling code here:
        //alter
        diag_alt_gen.setVisible(true);
    }//GEN-LAST:event_alt_genActionPerformed

    private void alt_gen_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_gen_butActionPerformed
        Generos genero = em.find(Generos.class, Integer.parseInt(alt_gen_id.getText()));

        em.getTransaction().begin();
          genero.setDESCRICAO(alt_gen_desc.getText());
        em.getTransaction().commit();

        diag_alt_gen.setVisible(false);
    }//GEN-LAST:event_alt_gen_butActionPerformed

    private void exc_gen_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_gen_butActionPerformed
        Generos genero = em.find(Generos.class, Integer.parseInt(exc_gen_id.getText()));
        em.getTransaction().begin();
        em.remove(genero);
        em.getTransaction().commit();

        diag_exc_gen.setVisible(false);
    }//GEN-LAST:event_exc_gen_butActionPerformed

    private void exc_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_genActionPerformed
        // TODO add your handling code here:
        diag_exc_gen.setVisible(true);
    }//GEN-LAST:event_exc_genActionPerformed

    private void cons_livActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_livActionPerformed
        // TODO add your handling code here:
        //consulta
        diag_cons_liv.setVisible(true);
    }//GEN-LAST:event_cons_livActionPerformed

    private void exc_livActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_livActionPerformed
        // TODO add your handling code here:
        diag_exc_liv.setVisible(true);
    }//GEN-LAST:event_exc_livActionPerformed

    private void alt_livActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_livActionPerformed
        // TODO add your handling code here:
        diag_alt_liv.setVisible(true);
    }//GEN-LAST:event_alt_livActionPerformed

    private void ins_livActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_livActionPerformed
        // TODO add your handling code here:
        diag_ins_liv.setVisible(true);
    }//GEN-LAST:event_ins_livActionPerformed

    private void cons_pedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_pedActionPerformed
        // TODO add your handling code here:
        diag_cons_ped.setVisible(true);
    }//GEN-LAST:event_cons_pedActionPerformed

    private void exc_pedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_pedActionPerformed
        // TODO add your handling code here:
        diag_exc_ped.setVisible(true);
    }//GEN-LAST:event_exc_pedActionPerformed

    private void alt_pedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_pedActionPerformed
        // TODO add your handling code here:
        diag_alt_ped.setVisible(true);
    }//GEN-LAST:event_alt_pedActionPerformed

    private void ins_pedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_pedActionPerformed
        // TODO add your handling code here:
        diag_ins_ped.setVisible(true);
    }//GEN-LAST:event_ins_pedActionPerformed

    private void ins_liv_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_liv_butActionPerformed
        Livros livro = new Livros();
        
        livro.setLIVRO_ID(Integer.parseInt(ins_liv_id.getText()));
        livro.setTITULO(ins_liv_tit.getText());
        livro.setAUTOR(ins_liv_aut.getText());
        livro.setEDITORA(ins_liv_edi.getText());
        livro.setANO(Integer.parseInt(ins_liv_ano.getText()));
        livro.setGENERO_ID(Integer.parseInt(ins_liv_gen.getText()));
        livro.setDESCRICAO(ins_liv_des.getText());
        livro.setPRECO(Double.parseDouble(ins_liv_pre.getText()));
        livro.setESTOQUE(Integer.parseInt(ins_liv_est.getText()));
        livro.setRESERVA(Integer.parseInt(ins_liv_res.getText()));
        
        em.getTransaction().begin();
        em.persist(livro);
        em.getTransaction().commit();
        
        diag_ins_liv.setVisible(false);
    }//GEN-LAST:event_ins_liv_butActionPerformed

    private void cons_liv__butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_liv__butActionPerformed
        Livros livro = em.find(Livros.class, Integer.parseInt(cons_liv_id.getText()));
        cons_liv_res.setText(livro.toString());
    }//GEN-LAST:event_cons_liv__butActionPerformed

    private void alt_liv_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_liv_butActionPerformed
        Livros livros = em.find(Livros.class, Integer.parseInt(alt_liv_id.getText()));

        em.getTransaction().begin();
            livros.setTITULO(ins_liv_tit.getText());
            livros.setAUTOR(ins_liv_aut.getText());
            livros.setEDITORA(ins_liv_edi.getText());
            livros.setANO(Integer.parseInt(ins_liv_ano.getText()));
            livros.setGENERO_ID(Integer.parseInt(ins_liv_gen.getText()));
            livros.setDESCRICAO(ins_liv_des.getText());
            livros.setPRECO(Double.parseDouble(ins_liv_pre.getText()));
            livros.setESTOQUE(Integer.parseInt(ins_liv_est.getText()));
            livros.setRESERVA(Integer.parseInt(ins_liv_res.getText()));
        em.getTransaction().commit();

        diag_alt_liv.setVisible(false);
    }//GEN-LAST:event_alt_liv_butActionPerformed

    private void exc_liv_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_liv_butActionPerformed
        Livros livro = em.find(Livros.class, Integer.parseInt(exc_liv_id.getText()));
        em.getTransaction().begin();
        em.remove(livro);
        em.getTransaction().commit();

        diag_exc_liv.setVisible(false);
    }//GEN-LAST:event_exc_liv_butActionPerformed

    private void ins_liv_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_liv_genActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_liv_genActionPerformed

    private void ins_ped_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_ped_butActionPerformed
        Pedidos pedido = new Pedidos();

        pedido.setPEDIDO_ID(Integer.parseInt(ins_ped_ped.getText()));
        pedido.setUSUARIO_ID(Integer.parseInt(ins_ped_usu.getText()));
        pedido.setDATA_PEDIDO(ins_ped_dat.getText());
        pedido.setTIPO_PAG(ins_ped_pag.getText());

        em.getTransaction().begin();
        em.persist(pedido);
        em.getTransaction().commit();

        diag_ins_ped.setVisible(false);
    }//GEN-LAST:event_ins_ped_butActionPerformed

    private void cons_ped_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_ped_butActionPerformed
        Pedidos pedido = em.find(Pedidos.class, Integer.parseInt(cons_ped_id.getText()));
        cons_ped_res.setText(pedido.toString());
    }//GEN-LAST:event_cons_ped_butActionPerformed

    private void alt_ped_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alt_ped_butActionPerformed
        Pedidos pedido = em.find(Pedidos.class, Integer.parseInt(alt_ped_ped.getText()));

        em.getTransaction().begin();
        
            pedido.setUSUARIO_ID(Integer.parseInt(alt_ped_usu.getText()));
            pedido.setDATA_PEDIDO(alt_ped_dat.getText());
            pedido.setTIPO_PAG(alt_ped_pag.getText());
            
        em.getTransaction().commit();

        diag_alt_ped.setVisible(false);
    }//GEN-LAST:event_alt_ped_butActionPerformed

    private void exc_ped_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exc_ped_butActionPerformed
        Pedidos pedido = em.find(Pedidos.class, Integer.parseInt(exc_ped_id.getText()));
        em.getTransaction().begin();
        em.remove(pedido);
        em.getTransaction().commit();

        diag_exc_ped.setVisible(false);
    }//GEN-LAST:event_exc_ped_butActionPerformed

    private void ins_ped_datActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_ped_datActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ins_ped_datActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    public Generos findGeneros(int id) {
        Generos genero = em.find(Generos.class, id);
        return genero;
    }

    public void finalize() {
        em.close();
        emf.close();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alt_gen;
    private javax.swing.JButton alt_gen_but;
    private javax.swing.JTextField alt_gen_desc;
    private javax.swing.JTextField alt_gen_id;
    private javax.swing.JButton alt_liv;
    private javax.swing.JTextField alt_liv_ano;
    private javax.swing.JTextField alt_liv_aut;
    private javax.swing.JButton alt_liv_but;
    private javax.swing.JTextField alt_liv_des;
    private javax.swing.JTextField alt_liv_edi;
    private javax.swing.JTextField alt_liv_est;
    private javax.swing.JTextField alt_liv_gen;
    private javax.swing.JTextField alt_liv_id;
    private javax.swing.JTextField alt_liv_pre;
    private javax.swing.JTextField alt_liv_res;
    private javax.swing.JTextField alt_liv_tit;
    private javax.swing.JButton alt_ped;
    private javax.swing.JButton alt_ped_but;
    private javax.swing.JTextField alt_ped_dat;
    private javax.swing.JTextField alt_ped_pag;
    private javax.swing.JTextField alt_ped_ped;
    private javax.swing.JTextField alt_ped_usu;
    private javax.swing.JButton cons_gen;
    private javax.swing.JButton cons_gen_but;
    private javax.swing.JTextField cons_gen_id;
    private javax.swing.JTextArea cons_gen_res;
    private javax.swing.JButton cons_liv;
    private javax.swing.JButton cons_liv__but;
    private javax.swing.JTextField cons_liv_id;
    private javax.swing.JTextArea cons_liv_res;
    private javax.swing.JButton cons_ped;
    private javax.swing.JButton cons_ped_but;
    private javax.swing.JTextField cons_ped_id;
    private javax.swing.JTextArea cons_ped_res;
    private javax.swing.JDialog diag_alt_gen;
    private javax.swing.JDialog diag_alt_liv;
    private javax.swing.JDialog diag_alt_ped;
    private javax.swing.JDialog diag_cons_gen;
    private javax.swing.JDialog diag_cons_liv;
    private javax.swing.JDialog diag_cons_ped;
    private javax.swing.JDialog diag_exc_gen;
    private javax.swing.JDialog diag_exc_liv;
    private javax.swing.JDialog diag_exc_ped;
    private javax.swing.JDialog diag_ins_gen;
    private javax.swing.JDialog diag_ins_liv;
    private javax.swing.JDialog diag_ins_ped;
    private javax.swing.JButton exc_gen;
    private javax.swing.JButton exc_gen_but;
    private javax.swing.JTextField exc_gen_id;
    private javax.swing.JButton exc_liv;
    private javax.swing.JButton exc_liv_but;
    private javax.swing.JTextField exc_liv_id;
    private javax.swing.JButton exc_ped;
    private javax.swing.JButton exc_ped_but;
    private javax.swing.JTextField exc_ped_id;
    private javax.swing.JButton ins_gen;
    private javax.swing.JButton ins_gen_but;
    private javax.swing.JTextField ins_gen_desc;
    private javax.swing.JTextField ins_gen_id;
    private javax.swing.JButton ins_liv;
    private javax.swing.JTextField ins_liv_ano;
    private javax.swing.JTextField ins_liv_aut;
    private javax.swing.JButton ins_liv_but;
    private javax.swing.JTextField ins_liv_des;
    private javax.swing.JTextField ins_liv_edi;
    private javax.swing.JTextField ins_liv_est;
    private javax.swing.JTextField ins_liv_gen;
    private javax.swing.JTextField ins_liv_id;
    private javax.swing.JTextField ins_liv_pre;
    private javax.swing.JTextField ins_liv_res;
    private javax.swing.JTextField ins_liv_tit;
    private javax.swing.JButton ins_ped;
    private javax.swing.JButton ins_ped_but;
    private javax.swing.JTextField ins_ped_dat;
    private javax.swing.JTextField ins_ped_pag;
    private javax.swing.JTextField ins_ped_ped;
    private javax.swing.JTextField ins_ped_usu;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lab_gen;
    private javax.swing.JLabel lab_liv;
    private javax.swing.JLabel lab_ped;
    // End of variables declaration//GEN-END:variables
}
